name: Cron Action
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */1 * * *'


jobs:
  promoapps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'
      - name: Install Requirements
        run: pip install -r requirements.txt
      - name: Run PromoApps
        run: python promoapps.py
        env:
          DESTINATION: ${{ secrets.DESTINATION }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          FEED_URL: ${{ secrets.FEED_URL }}
          BLUESKY_PASSWORD: ${{ secrets.BLUESKY_PASSWORD }}
